### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by frankmorgner**
- adds OSX instructions
- minor debugging/performance improvements
- fixes some windows build problems
- should fix compilation of crypto++ on android

### CODE REVIEW

**Comment by eriknellessen** [comment]
In the file eIDClientCore/android/Makefile, line 93 (https://github.com/BeID-lab/eIDClientCore/pull/74/files#diff-be8e95fe3c5c5544a6e911928865eb75R93):
sed -i '' 's/^_ANDROID_API=\"android-.*/_ANDROID_API=\"'$(ANDROID_API)'\"/' setenv-android.sh &&\

Please remove the '' after -i, i.e.
```
sed -i 's/^_ANDROID_API=\"android-.*/_ANDROID_API=\"'$(ANDROID_API)'\"/' setenv-android.sh &&\
```
instead of
```
sed -i '' 's/^_ANDROID_API=\"android-.*/_ANDROID_API=\"'$(ANDROID_API)'\"/' setenv-android.sh &&\
```

It is the reason, why Travis CI build is failing:
```
Archive:  Setenv-android.sh.zip
  inflating: setenv-android.sh       
sed: can't read s/^_ANDROID_API=\"android-.*/_ANDROID_API=\"android-19\"/: No such file or directory
make[1]: *** [/home/travis/build/BeID-lab/eIDClientCore/eIDClientCore/android/eIDClientCore-0.2_arm/lib/libcryptopp.so] Error 2
```
After that, the other make command is executed (I wrote you an e-mail about this on 11th of November), which fails, as it tries to unpack Setenv-android.sh.zip again:
```
Archive:  Setenv-android.sh.zip
replace setenv-android.sh? [y]es, [n]o, [A]ll, [N]one, [r]ename: 

No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by frankmorgner** [comment]
hmm, in my case `sed` was used on OS X, which requires the additional argument, see http://stackoverflow.com/questions/4247068/sed-command-failing-on-mac-but-works-on-linux. It's fixed now.

**Comment by eriknellessen** [comment]
We fixed the CryptoPP cross-compiling for android problem in  dc31b2075e67f2ab83e600e5d0786cd3d166d692. We also do the new procedure with the GNUmakefile-cross now. So the changes of 7da8d9a87f7fd313f7242bd8e8bb40c5343f42f7 are no longer useful.

Please resolve the merge conflict and merge your pull request.

**Comment by frankmorgner** [comment]
done

**Pull request merged**
