### PR TITLE
Some better statistics output and correction of one error check

### PR DESCRIPTION
**Pull request by psytester**
- each eID Dialog will have a "visible"  separator and number of currect request on stdout. It's for faster and better overview.
- output of single dialog duration "Laufzeit:" is moved to central place, otherwise the error cases do not get such duration time
- print out Overall time over all Loops
- "Wait two seconds" was moved after the complete eiD Dialog handling, as we maybe need a delay between two eID dialogs
- Check of finalSAML-IF <errorStatus> element and SOAP-IF  <ResultMajor> to detect if the eID dialog was finally ok or faulty
- ouput of error code corrected:
value is taken in line
```
1261                           retValue = getSamlResponse2(response); 
```

But printf has used
```
1263                           printf("%s:%d Error %08lX\n", __FILE__, __LINE__, g_samlResponseReturncode);
```
-- changed into -->
```
printf("%s:%d Error %08lX\n", __FILE__, __LINE__, retValue);
```

### CODE REVIEW

**Comment by wolfmueller** [comment]
Some remarks:
* The used locale is EN-US in the project. Therefore e.g. "Gesamte Dauer ueber ..." does not fit well.
* I would propose to define a macro for START|END of separators in order to get a uniform layout on all occurrences.
* I am not quite sure about your intention which type of time you want to measure. 
Differences in

**Comment by psytester** [comment]
I'm fine for any unique layout, as long as I can see separated on console the start and the end of each eID Dialog.
If you change "Gesamte Dauer ueber ...", then do it for "Laufzeit" too :)
My intention is to measure each single eID Dialog and the total time of <XXX> requests.
It's used for load and stress tests and for long duration tests.
For sure we measure the time of service provider and eID Service together, but that's ok for me as itÄs the overall time from triggering the eID until the final result.
If you want you can add more differentiated  and detailed statistics for the processing time withing SP and eID Service. (means time within "Browser" and within the eID Client part)
Please keep the 2 seconds sleep time, but make it changeable via an new command line Option.
I use that to make "real stress" with sleep time = zero seconds, some moderate tests with (default) two seconds or some long duration tests with 20 seconds sleep time.

**Comment by psytester** [comment]
I have updated the source with correct locale

**Comment by frankmorgner** [comment]
@wolfmueller does the source code comment regarding the sleep answer your question?

looks OK for me

**Comment by frankmorgner** [comment]
the two commits should be crushed into one, though

**Comment by psytester** [comment]
If I would know how to merge commits I would do ;-)
Some trial and error in Git Shell did not work for me and you know I have usually Browser access only

**Comment by frankmorgner** [comment]
see https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/ for example

**Comment by psytester** [comment]
Arghh, one more commit in that branch
I will start a new pull request.

**Pull request closed without merging**
